defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  encoding: utf8
  host: localhost

development:
  <<: *defaults
  database: courbedepoids_dev

test:
  <<: *defaults
  database: courbedepoids_test

staging:
  <<: *defaults
  database: courbedepoids_staging
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *defaults
  database: courbedepoids_production
  socket: /var/run/mysqld/mysqld.sock
